window.Words = [
  { "greek": "άντρας", "translation": "man" },
  { "greek": "ήλιος", "translation": "sun," },
  { "greek": "ήχος", "translation": "sound" },
  { "greek": "αγώνας", "translation": "match, game" },
  { "greek": "αθλητισμός", "translation": "sports" },
  { "greek": "αναπτήρας", "translation": "lighter" },
  { "greek": "ανταγωνισμός", "translation": "contest, competition" },
  { "greek": "αποδέκτης", "translation": "recipient, receiver" },
  { "greek": "αρακάς", "translation": "pea" },
  { "greek": "αριθμός", "translation": "number" },
  { "greek": "βάλτος", "translation": "swamp, marsh" },
  { "greek": "βήχας", "translation": "cough" },
  { "greek": "βαθμός", "translation": "grade" },
  { "greek": "γάμος", "translation": "wedding" },
  { "greek": "γέρος", "translation": "old man" },
  { "greek": "γείτονας", "translation": "neightbour" },
  { "greek": "γιος", "translation": "son" },
  { "greek": "γύρος", "translation": "gyros" },
  { "greek": "διάλογος", "translation": "dialogue" },
  { "greek": "δρόμος", "translation": "road, street" },
  { "greek": "ενικός αριθμός", "translation": "singular number" },
  { "greek": "θείος", "translation": "uncle" },
  { "greek": "θόρυβος", "translation": "noise" },
  { "greek": "κήπος", "translation": "garden" },
  { "greek": "καθρέφτης", "translation": "mirror" },
  { "greek": "καιρός", "translation": "weather" },
  { "greek": "καναπές", "translation": "sofa" },
  { "greek": "κανόνας", "translation": "rule" },
  { "greek": "κατάλογος", "translation": "catalogue" },
  { "greek": "καφές", "translation": "coffee" },
  { "greek": "κινηματογράφος", "translation": "cinema" },
  { "greek": "κρεοπώλης", "translation": "butcher" },
  { "greek": "κόκορας", "translation": "rooster" },
  { "greek": "κόσμος", "translation": "people, crowd" },
  { "greek": "κύκλος", "translation": "cicrle" },
  { "greek": "κύριος", "translation": "sir, mister" },
  { "greek": "λαβύρινθος", "translation": "labyrinth" },
  { "greek": "λαγός", "translation": "hare" },
  { "greek": "λογαριασμός", "translation": "account" },
  { "greek": "λόγος", "translation": "reason" },
  { "greek": "λύκος", "translation": "wolf" },
  { "greek": "μήνας", "translation": "month" },
  { "greek": "μανάβης", "translation": "grocer" },
  { "greek": "μεσίτης", "translation": "broker" },
  { "greek": "μισθός", "translation": "salary" },
  { "greek": "μπακάλης", "translation": "grocer" },
  { "greek": "μπαμπάς", "translation": "father" },
  { "greek": "ξενώνας", "translation": "hostel" },
  { "greek": "ουρανός", "translation": "sky" },
  { "greek": "πάγκος", "translation": "bench" },
  { "greek": "παππούς", "translation": "grandfather" },
  { "greek": "πατέρας", "translation": "father" },
  { "greek": "πληθυντικός", "translation": "plural (number)" },
  { "greek": "προορισμός", "translation": "destination" },
  { "greek": "πυρετός", "translation": "fever" },
  { "greek": "πόνος", "translation": "pain" },
  { "greek": "πύργος", "translation": "tower" },
  { "greek": "ρόλος", "translation": "role, part" },
  { "greek": "σερβιτόρος", "translation": "waiter" },
  { "greek": "σκύλος", "translation": "dog" },
  { "greek": "στίχος", "translation": "verse" },
  { "greek": "συγγραφέας", "translation": "author" },
  { "greek": "τίτλος", "translation": "title" },
  { "greek": "ταμίας", "translation": "cashier" },
  { "greek": "τοίχος", "translation": "wall" },
  { "greek": "τουρισμός", "translation": "tourism" },
  { "greek": "τρόπος", "translation": "way" },
  { "greek": "τόμος", "translation": "volume" },
  { "greek": "τόνος", "translation": "accent mark" },
  { "greek": "φάκελος", "translation": "envelope" },
  { "greek": "φθόγγος", "translation": "sound" },
  { "greek": "φούρνος", "translation": "the baker’s, bakery" },
  { "greek": "χάρακας", "translation": "ruler" },
  { "greek": "χάρτης", "translation": "map" },
  { "greek": "χαρακτήρας", "translation": "character" },
  { "greek": "χειμώνας", "translation": "winter" },
  { "greek": "χορός", "translation": "dancing" },
  { "greek": "χρήστης", "translation": "user" },
  { "greek": "χυμός", "translation": "uice" },
  { "greek": "χώρος", "translation": "space, room" },
  { "greek": "όροφος", "translation": "floor" },
  { "greek": "ύπνος", "translation": "sleep" },
  { "greek": "ώμος", "translation": "shoulder" },
  { "greek": "άνοιξη", "translation": "spring" },
  { "greek": "άσκηση", "translation": "task, exercise" },
  { "greek": "ίντερνετ] διαδρομή", "translation": "way, path, route" },
  { "greek": "αίτηση", "translation": "application, application form" },
  { "greek": "αγάπη", "translation": "love" },
  { "greek": "ακρόαση", "translation": "listening" },
  { "greek": "ακτή", "translation": "beach" },
  { "greek": "αλλαγή", "translation": "change" },
  { "greek": "ανάγκη", "translation": "need, necessity" },
  { "greek": "ανάγνωση", "translation": "reading" },
  { "greek": "ανάληψη", "translation": "withdrawal" },
  { "greek": "απάντηση", "translation": "answer, respond, reply" },
  { "greek": "αποδοχή", "translation": "acceptance" },
  { "greek": "απόσταση", "translation": "distance" },
  { "greek": "απόφαση", "translation": "decision" },
  { "greek": "αρχή", "translation": "beginning, start" },
  { "greek": "ασπιρίνη", "translation": "aspirin" },
  { "greek": "αυλή", "translation": "yard" },
  { "greek": "βάση", "translation": "base" },
  { "greek": "βιβλιοθήκη", "translation": "library" },
  { "greek": "βροχή", "translation": "rain" },
  { "greek": "βρύση", "translation": "tap" },
  { "greek": "γέννηση", "translation": "birth" },
  { "greek": "γιορτή", "translation": "feast, celebration" },
  { "greek": "γνώμη", "translation": "opinion" },
  { "greek": "γνώση", "translation": "knowledge" },
  { "greek": "γραμμή", "translation": "line" },
  { "greek": "γραμματική", "translation": "grammar" },
  { "greek": "γραφή", "translation": "writing" },
  { "greek": "γυμναστική", "translation": "gymnastics" },
  { "greek": "δάφνη", "translation": "laurel" },
  { "greek": "διαμονή", "translation": "stay, accomodation" },
  { "greek": "διατροφή", "translation": "nutrition" },
  { "greek": "διαφήμιση", "translation": "advertisment, ad [see also" },
  { "greek": "διεύθυνση", "translation": "address" },
  { "greek": "δύναμη", "translation": "power" },
  { "greek": "επίσκεψη", "translation": "visit" },
  { "greek": "επιλογή", "translation": "choice" },
  { "greek": "επιστήμη", "translation": "science" },
  { "greek": "εποχή", "translation": "season" },
  { "greek": "ερώτηση", "translation": "question" },
  { "greek": "ευχή", "translation": "wish" },
  { "greek": "ζάχαρη", "translation": "sugar" },
  { "greek": "ζέστη", "translation": "heat" },
  { "greek": "ζωή", "translation": "life" },
  { "greek": "ζωγραφική", "translation": "painting" },
  { "greek": "θέρμανση", "translation": "heating" },
  { "greek": "θέση", "translation": "place, position" },
  { "greek": "ιατρική", "translation": "medicine" },
  { "greek": "καθυστέρηση", "translation": "delay" },
  { "greek": "κατάθεση", "translation": "deposit" },
  { "greek": "κατάσταση", "translation": "situation" },
  { "greek": "κατασκήνωση", "translation": "camp" },
  { "greek": "κατεύθυνση", "translation": "direction" },
  { "greek": "κόρη", "translation": "daughter" },
  { "greek": "λέξη", "translation": "word" },
  { "greek": "λίμνη", "translation": "lake" },
  { "greek": "λύπη", "translation": "sadness" },
  { "greek": "μέση", "translation": "waist" },
  { "greek": "μηχανή", "translation": "machine" },
  { "greek": "μνήμη", "translation": "memory" },
  { "greek": "μουσική", "translation": "music" },
  { "greek": "μύτη", "translation": "nose" },
  { "greek": "οικοδομή", "translation": "building" },
  { "greek": "περιοχή", "translation": "region" },
  { "greek": "προσοχή", "translation": "attention" },
  { "greek": "πρόσκληση", "translation": "invitation" },
  { "greek": "πρόταση", "translation": "sentence" },
  { "greek": "πόλη", "translation": "city" },
  { "greek": "σκόνη", "translation": "dust" },
  { "greek": "στήλη", "translation": "column" },
  { "greek": "συγνώμη", "translation": "apology" },
  { "greek": "συζήτηση", "translation": "discussion" },
  { "greek": "συμβουλή", "translation": "advice" },
  { "greek": "συνέντευξη", "translation": "interview" },
  { "greek": "συνταγή", "translation": "recipe" },
  { "greek": "συσκευή", "translation": "device" },
  { "greek": "σχέση", "translation": "relation" },
  { "greek": "σύγκριση", "translation": "comparison" },
  { "greek": "τάξη", "translation": "classroom" },
  { "greek": "τηλεόραση", "translation": "television" },
  { "greek": "τιμή", "translation": "price" },
  { "greek": "τσάντα σχολική", "translation": "schoolbag" },
  { "greek": "υπογραφή", "translation": "signature" },
  { "greek": "υπομονή", "translation": "patience" },
  { "greek": "φήμη", "translation": "rumor" },
  { "greek": "φράση", "translation": "phrase" },
  { "greek": "φωνή", "translation": "voice" },
  { "greek": "φωτογραφική μηχανή", "translation": "camera" },
  { "greek": "φύση", "translation": "nature" },
  { "greek": "χρήση", "translation": "use" },
  { "greek": "έφηβος", "translation": "teenager" },
  { "greek": "αθλητής", "translation": "athlete" },
  { "greek": "απόφοιτος", "translation": "graduate" },
  { "greek": "ασθενής", "translation": "patient" },
  { "greek": "γιατρός", "translation": "doctor" },
  { "greek": "γραμματέας", "translation": "secretary" },
  { "greek": "δημοσιογράφος", "translation": "ournalist" },
  { "greek": "δικηγόρος", "translation": "lawer" },
  { "greek": "κάτοικος", "translation": "resident, inhabitant" },
  { "greek": "καθηγητής", "translation": "teacher" },
  { "greek": "κομμωτής", "translation": "hair dresser" },
  { "greek": "μάγειρας", "translation": "cook" },
  { "greek": "μαθητής", "translation": "pupil, student" },
  { "greek": "νικητής", "translation": "winner" },
  { "greek": "νοσοκόμος", "translation": "nurse" },
  { "greek": "ξάδερφος", "translation": "cousin" },
  { "greek": "οδηγός", "translation": "guide" },
  { "greek": "παθολόγος", "translation": "pathologist" },
  { "greek": "παιδίατρος", "translation": "pediatrician" },
  { "greek": "πελάτης", "translation": "client" },
  { "greek": "πωλητής", "translation": "salesperson, shop assistant" },
  { "greek": "συμμαθητής", "translation": "school mate" },
  { "greek": "συνάδελφος", "translation": "colleague" },
  { "greek": "τουρίστας", "translation": "tourist" },
  { "greek": "φίλος", "translation": "friend" },
  { "greek": "φαρμακοποιός", "translation": "pharmacist" },
  { "greek": "φοιτητής", "translation": "student" },
  { "greek": "φούρναρης", "translation": "baker" },
  { "greek": "χειρούργος", "translation": "surgeon" }
];
