window.Words = [
  { "greek": "άντρας", "translation": "man" },
  { "greek": "ήλιος", "translation": "sun," },
  { "greek": "ήχος", "translation": "sound" },
  { "greek": "αγώνας", "translation": "match, game" },
  { "greek": "αθλητισμός", "translation": "sports" },
  { "greek": "αναπτήρας", "translation": "lighter" },
  { "greek": "ανταγωνισμός", "translation": "contest, competition" },
  { "greek": "αποδέκτης", "translation": "recipient, receiver" },
  { "greek": "αρακάς", "translation": "pea" },
  { "greek": "αριθμός", "translation": "number" },
  { "greek": "βάλτος", "translation": "swamp, marsh" },
  
  { "greek": "βήχας", "translation": "cough" },
  { "greek": "βαθμός", "translation": "grade" },
  { "greek": "γάμος", "translation": "wedding" },
  { "greek": "γέρος", "translation": "old man" },
  { "greek": "γείτονας", "translation": "neightbour" },
  { "greek": "γιος", "translation": "son" },
  { "greek": "γύρος", "translation": "gyros" },
  { "greek": "διάλογος", "translation": "dialogue" },
  { "greek": "δρόμος", "translation": "road, street" },
  { "greek": "ενικός αριθμός", "translation": "singular number" },
  { "greek": "θείος", "translation": "uncle" },
  { "greek": "θόρυβος", "translation": "noise" },
  { "greek": "κήπος", "translation": "garden" },
  { "greek": "καθρέφτης", "translation": "mirror" },
  { "greek": "καιρός", "translation": "weather" },
  { "greek": "καναπές", "translation": "sofa" },
  { "greek": "κανόνας", "translation": "rule" },
  { "greek": "κατάλογος", "translation": "catalogue" },
  { "greek": "καφές", "translation": "coffee" },
  { "greek": "κινηματογράφος", "translation": "cinema" },
  { "greek": "κρεοπώλης", "translation": "butcher" },
  { "greek": "κόκορας", "translation": "rooster" },
  { "greek": "κόσμος", "translation": "people, crowd" },
  { "greek": "κύκλος", "translation": "cicrle" },
  { "greek": "κύριος", "translation": "sir, mister" },
  { "greek": "λαβύρινθος", "translation": "labyrinth" },
  { "greek": "λαγός", "translation": "hare" },
  { "greek": "λογαριασμός", "translation": "account" },
  { "greek": "λόγος", "translation": "reason" },
  { "greek": "λύκος", "translation": "wolf" },
  { "greek": "μήνας", "translation": "month" },
  { "greek": "μανάβης", "translation": "grocer" },
  { "greek": "μεσίτης", "translation": "broker" },
  { "greek": "μισθός", "translation": "salary" },
  { "greek": "μπακάλης", "translation": "grocer" },
  { "greek": "μπαμπάς", "translation": "father" },
  { "greek": "ξενώνας", "translation": "hostel" },
  { "greek": "ουρανός", "translation": "sky" },
  { "greek": "πάγκος", "translation": "bench" },
  { "greek": "παππούς", "translation": "grandfather" },
  { "greek": "πατέρας", "translation": "father" },
  { "greek": "πληθυντικός", "translation": "plural (number)" },
  { "greek": "προορισμός", "translation": "destination" },
  { "greek": "πυρετός", "translation": "fever" },
  { "greek": "πόνος", "translation": "pain" },
  { "greek": "πύργος", "translation": "tower" },
  { "greek": "ρόλος", "translation": "role, part" },
  { "greek": "σερβιτόρος", "translation": "waiter" },
  { "greek": "σκύλος", "translation": "dog" },
  { "greek": "στίχος", "translation": "verse" },
  { "greek": "συγγραφέας", "translation": "author" },
  { "greek": "τίτλος", "translation": "title" },
  { "greek": "ταμίας", "translation": "cashier" },
  { "greek": "τοίχος", "translation": "wall" },
  { "greek": "τουρισμός", "translation": "tourism" },
  { "greek": "τρόπος", "translation": "way" },
  { "greek": "τόμος", "translation": "volume" },
  { "greek": "τόνος", "translation": "accent mark" },
  { "greek": "φάκελος", "translation": "envelope" },
  { "greek": "φθόγγος", "translation": "sound" },
  { "greek": "φούρνος", "translation": "the baker’s, bakery" },
  { "greek": "χάρακας", "translation": "ruler" },
  { "greek": "χάρτης", "translation": "map" },
  { "greek": "χαρακτήρας", "translation": "character" },
  { "greek": "χειμώνας", "translation": "winter" },
  { "greek": "χορός", "translation": "dancing" },
  { "greek": "χρήστης", "translation": "user" },
  { "greek": "χυμός", "translation": "uice" },
  { "greek": "χώρος", "translation": "space, room" },
  { "greek": "όροφος", "translation": "floor" },
  { "greek": "ύπνος", "translation": "sleep" },
  { "greek": "ώμος", "translation": "shoulder" }
   
];
