window.Words = [
  { "greek": "άντρας", "translation": "man", "tags": "A1;noun;masculine" },
  { "greek": "ήλιος", "translation": "sun,", "tags": "A1;noun;masculine" },
  { "greek": "ήχος", "translation": "sound", "tags": "A1;noun;masculine" },
  { "greek": "αγώνας", "translation": "match, game", "tags": "A1;noun;masculine" },
  { "greek": "αθλητισμός", "translation": "sports", "tags": "A1;noun;masculine" },
  { "greek": "αναπτήρας", "translation": "lighter", "tags": "A1;noun;masculine" },
  { "greek": "ανταγωνισμός", "translation": "contest, competition", "tags": "A1;noun;masculine" },
  { "greek": "αποδέκτης", "translation": "recipient, receiver", "tags": "A1;noun;masculine" },
  { "greek": "αρακάς", "translation": "pea", "tags": "A1;noun;masculine" },
  { "greek": "αριθμός", "translation": "number", "tags": "A1;noun;masculine" },
  { "greek": "βάλτος", "translation": "swamp, marsh", "tags": "A1;noun;masculine" },
  { "greek": "βήχας", "translation": "cough", "tags": "A1;noun;masculine" },
  { "greek": "βαθμός", "translation": "grade", "tags": "A1;noun;masculine" },
  { "greek": "γάμος", "translation": "wedding", "tags": "A1;noun;masculine" },
  { "greek": "γέρος", "translation": "old man", "tags": "A1;noun;masculine" },
  { "greek": "γείτονας", "translation": "neightbour", "tags": "A1;noun;masculine" },
  { "greek": "γιος", "translation": "son", "tags": "A1;noun;masculine" },
  { "greek": "γύρος", "translation": "gyros", "tags": "A1;noun;masculine" },
  { "greek": "διάλογος", "translation": "dialogue", "tags": "A1;noun;masculine" },
  { "greek": "δρόμος", "translation": "road, street", "tags": "A1;noun;masculine" },
  { "greek": "ενικός αριθμός", "translation": "singular number", "tags": "A1;noun;masculine" },
  { "greek": "θείος", "translation": "uncle", "tags": "A1;noun;masculine" },
  { "greek": "θόρυβος", "translation": "noise", "tags": "A1;noun;masculine" },
  { "greek": "κήπος", "translation": "garden", "tags": "A1;noun;masculine" },
  { "greek": "καθρέφτης", "translation": "mirror", "tags": "A1;noun;masculine" },
  { "greek": "καιρός", "translation": "weather", "tags": "A1;noun;masculine" },
  { "greek": "καναπές", "translation": "sofa", "tags": "A1;noun;masculine" },
  { "greek": "κανόνας", "translation": "rule", "tags": "A1;noun;masculine" },
  { "greek": "κατάλογος", "translation": "catalogue", "tags": "A1;noun;masculine" },
  { "greek": "καφές", "translation": "coffee", "tags": "A1;noun;masculine" },
  { "greek": "κινηματογράφος", "translation": "cinema", "tags": "A1;noun;masculine" },
  { "greek": "κρεοπώλης", "translation": "butcher", "tags": "A1;noun;masculine" },
  { "greek": "κόκορας", "translation": "rooster", "tags": "A1;noun;masculine" },
  { "greek": "κόσμος", "translation": "people, crowd", "tags": "A1;noun;masculine" },
  { "greek": "κύκλος", "translation": "cicrle", "tags": "A1;noun;masculine" },
  { "greek": "κύριος", "translation": "sir, mister", "tags": "A1;noun;masculine" },
  { "greek": "λαβύρινθος", "translation": "labyrinth", "tags": "A1;noun;masculine" },
  { "greek": "λαγός", "translation": "hare", "tags": "A1;noun;masculine" },
  { "greek": "λογαριασμός", "translation": "account", "tags": "A1;noun;masculine" },
  { "greek": "λόγος", "translation": "reason", "tags": "A1;noun;masculine" },
  { "greek": "λύκος", "translation": "wolf", "tags": "A1;noun;masculine" },
  { "greek": "μήνας", "translation": "month", "tags": "A1;noun;masculine" },
  { "greek": "μανάβης", "translation": "grocer", "tags": "A1;noun;masculine" },
  { "greek": "μεσίτης", "translation": "broker", "tags": "A1;noun;masculine" },
  { "greek": "μισθός", "translation": "salary", "tags": "A1;noun;masculine" },
  { "greek": "μπακάλης", "translation": "grocer", "tags": "A1;noun;masculine" },
  { "greek": "μπαμπάς", "translation": "father", "tags": "A1;noun;masculine" },
  { "greek": "ξενώνας", "translation": "hostel", "tags": "A1;noun;masculine" },
  { "greek": "ουρανός", "translation": "sky", "tags": "A1;noun;masculine" },
  { "greek": "πάγκος", "translation": "bench", "tags": "A1;noun;masculine" },
  { "greek": "παππούς", "translation": "grandfather", "tags": "A1;noun;masculine" },
  { "greek": "πατέρας", "translation": "father", "tags": "A1;noun;masculine" },
  { "greek": "πληθυντικός", "translation": "plural (number)", "tags": "A1;noun;masculine" },
  { "greek": "προορισμός", "translation": "destination", "tags": "A1;noun;masculine" },
  { "greek": "πυρετός", "translation": "fever", "tags": "A1;noun;masculine" },
  { "greek": "πόνος", "translation": "pain", "tags": "A1;noun;masculine" },
  { "greek": "πύργος", "translation": "tower", "tags": "A1;noun;masculine" },
  { "greek": "ρόλος", "translation": "role, part", "tags": "A1;noun;masculine" },
  { "greek": "σερβιτόρος", "translation": "waiter", "tags": "A1;noun;masculine" },
  { "greek": "σκύλος", "translation": "dog", "tags": "A1;noun;masculine" },
  { "greek": "στίχος", "translation": "verse", "tags": "A1;noun;masculine" },
  { "greek": "συγγραφέας", "translation": "author", "tags": "A1;noun;masculine" },
  { "greek": "τίτλος", "translation": "title", "tags": "A1;noun;masculine" },
  { "greek": "ταμίας", "translation": "cashier", "tags": "A1;noun;masculine" },
  { "greek": "τοίχος", "translation": "wall", "tags": "A1;noun;masculine" },
  { "greek": "τουρισμός", "translation": "tourism", "tags": "A1;noun;masculine" },
  { "greek": "τρόπος", "translation": "way", "tags": "A1;noun;masculine" },
  { "greek": "τόμος", "translation": "volume", "tags": "A1;noun;masculine" },
  { "greek": "τόνος", "translation": "accent mark", "tags": "A1;noun;masculine" },
  { "greek": "φάκελος", "translation": "envelope", "tags": "A1;noun;masculine" },
  { "greek": "φθόγγος", "translation": "sound", "tags": "A1;noun;masculine" },
  { "greek": "φούρνος", "translation": "the baker’s, bakery", "tags": "A1;noun;masculine" },
  { "greek": "χάρακας", "translation": "ruler", "tags": "A1;noun;masculine" },
  { "greek": "χάρτης", "translation": "map", "tags": "A1;noun;masculine" },
  { "greek": "χαρακτήρας", "translation": "character", "tags": "A1;noun;masculine" },
  { "greek": "χειμώνας", "translation": "winter", "tags": "A1;noun;masculine" },
  { "greek": "χορός", "translation": "dancing", "tags": "A1;noun;masculine" },
  { "greek": "χρήστης", "translation": "user", "tags": "A1;noun;masculine" },
  { "greek": "χυμός", "translation": "uice", "tags": "A1;noun;masculine" },
  { "greek": "χώρος", "translation": "space, room", "tags": "A1;noun;masculine" },
  { "greek": "όροφος", "translation": "floor", "tags": "A1;noun;masculine" },
  { "greek": "ύπνος", "translation": "sleep", "tags": "A1;noun;masculine" },
  { "greek": "ώμος", "translation": "shoulder", "tags": "A1;noun;masculine" },
  { "greek": "άνοιξη", "translation": "spring", "tags": "A1;noun;feminine-eta" },
  { "greek": "άσκηση", "translation": "task, exercise", "tags": "A1;noun;feminine-eta" },
  { "greek": "ίντερνετ] διαδρομή", "translation": "way, path, route", "tags": "A1;noun;feminine-eta" },
  { "greek": "αίτηση", "translation": "application, application form", "tags": "A1;noun;feminine-eta" },
  { "greek": "αγάπη", "translation": "love", "tags": "A1;noun;feminine-eta" },
  { "greek": "ακρόαση", "translation": "listening", "tags": "A1;noun;feminine-eta" },
  { "greek": "ακτή", "translation": "beach", "tags": "A1;noun;feminine-eta" },
  { "greek": "αλλαγή", "translation": "change", "tags": "A1;noun;feminine-eta" },
  { "greek": "ανάγκη", "translation": "need, necessity", "tags": "A1;noun;feminine-eta" },
  { "greek": "ανάγνωση", "translation": "reading", "tags": "A1;noun;feminine-eta" },
  { "greek": "ανάληψη", "translation": "withdrawal", "tags": "A1;noun;feminine-eta" },
  { "greek": "απάντηση", "translation": "answer, respond, reply", "tags": "A1;noun;feminine-eta" },
  { "greek": "αποδοχή", "translation": "acceptance", "tags": "A1;noun;feminine-eta" },
  { "greek": "απόσταση", "translation": "distance", "tags": "A1;noun;feminine-eta" },
  { "greek": "απόφαση", "translation": "decision", "tags": "A1;noun;feminine-eta" },
  { "greek": "αρχή", "translation": "beginning, start", "tags": "A1;noun;feminine-eta" },
  { "greek": "ασπιρίνη", "translation": "aspirin", "tags": "A1;noun;feminine-eta" },
  { "greek": "αυλή", "translation": "yard", "tags": "A1;noun;feminine-eta" },
  { "greek": "βάση", "translation": "base", "tags": "A1;noun;feminine-eta" },
  { "greek": "βιβλιοθήκη", "translation": "library", "tags": "A1;noun;feminine-eta" },
  { "greek": "βροχή", "translation": "rain", "tags": "A1;noun;feminine-eta" },
  { "greek": "βρύση", "translation": "tap", "tags": "A1;noun;feminine-eta" },
  { "greek": "γέννηση", "translation": "birth", "tags": "A1;noun;feminine-eta" },
  { "greek": "γιορτή", "translation": "feast, celebration", "tags": "A1;noun;feminine-eta" },
  { "greek": "γνώμη", "translation": "opinion", "tags": "A1;noun;feminine-eta" },
  { "greek": "γνώση", "translation": "knowledge", "tags": "A1;noun;feminine-eta" },
  { "greek": "γραμμή", "translation": "line", "tags": "A1;noun;feminine-eta" },
  { "greek": "γραμματική", "translation": "grammar", "tags": "A1;noun;feminine-eta" },
  { "greek": "γραφή", "translation": "writing", "tags": "A1;noun;feminine-eta" },
  { "greek": "γυμναστική", "translation": "gymnastics", "tags": "A1;noun;feminine-eta" },
  { "greek": "δάφνη", "translation": "laurel", "tags": "A1;noun;feminine-eta" },
  { "greek": "διαμονή", "translation": "stay, accomodation", "tags": "A1;noun;feminine-eta" },
  { "greek": "διατροφή", "translation": "nutrition", "tags": "A1;noun;feminine-eta" },
  { "greek": "διαφήμιση", "translation": "advertisment, ad [see also", "tags": "A1;noun;feminine-eta" },
  { "greek": "διεύθυνση", "translation": "address", "tags": "A1;noun;feminine-eta" },
  { "greek": "δύναμη", "translation": "power", "tags": "A1;noun;feminine-eta" },
  { "greek": "επίσκεψη", "translation": "visit", "tags": "A1;noun;feminine-eta" },
  { "greek": "επιλογή", "translation": "choice", "tags": "A1;noun;feminine-eta" },
  { "greek": "επιστήμη", "translation": "science", "tags": "A1;noun;feminine-eta" },
  { "greek": "εποχή", "translation": "season", "tags": "A1;noun;feminine-eta" },
  { "greek": "ερώτηση", "translation": "question", "tags": "A1;noun;feminine-eta" },
  { "greek": "ευχή", "translation": "wish", "tags": "A1;noun;feminine-eta" },
  { "greek": "ζάχαρη", "translation": "sugar", "tags": "A1;noun;feminine-eta" },
  { "greek": "ζέστη", "translation": "heat", "tags": "A1;noun;feminine-eta" },
  { "greek": "ζωή", "translation": "life", "tags": "A1;noun;feminine-eta" },
  { "greek": "ζωγραφική", "translation": "painting", "tags": "A1;noun;feminine-eta" },
  { "greek": "θέρμανση", "translation": "heating", "tags": "A1;noun;feminine-eta" },
  { "greek": "θέση", "translation": "place, position", "tags": "A1;noun;feminine-eta" },
  { "greek": "ιατρική", "translation": "medicine", "tags": "A1;noun;feminine-eta" },
  { "greek": "καθυστέρηση", "translation": "delay", "tags": "A1;noun;feminine-eta" },
  { "greek": "κατάθεση", "translation": "deposit", "tags": "A1;noun;feminine-eta" },
  { "greek": "κατάσταση", "translation": "situation", "tags": "A1;noun;feminine-eta" },
  { "greek": "κατασκήνωση", "translation": "camp", "tags": "A1;noun;feminine-eta" },
  { "greek": "κατεύθυνση", "translation": "direction", "tags": "A1;noun;feminine-eta" },
  { "greek": "κόρη", "translation": "daughter", "tags": "A1;noun;feminine-eta" },
  { "greek": "λέξη", "translation": "word", "tags": "A1;noun;feminine-eta" },
  { "greek": "λίμνη", "translation": "lake", "tags": "A1;noun;feminine-eta" },
  { "greek": "λύπη", "translation": "sadness", "tags": "A1;noun;feminine-eta" },
  { "greek": "μέση", "translation": "waist", "tags": "A1;noun;feminine-eta" },
  { "greek": "μηχανή", "translation": "machine", "tags": "A1;noun;feminine-eta" },
  { "greek": "μνήμη", "translation": "memory", "tags": "A1;noun;feminine-eta" },
  { "greek": "μουσική", "translation": "music", "tags": "A1;noun;feminine-eta" },
  { "greek": "μύτη", "translation": "nose", "tags": "A1;noun;feminine-eta" },
  { "greek": "οικοδομή", "translation": "building", "tags": "A1;noun;feminine-eta" },
  { "greek": "περιοχή", "translation": "region", "tags": "A1;noun;feminine-eta" },
  { "greek": "προσοχή", "translation": "attention", "tags": "A1;noun;feminine-eta" },
  { "greek": "πρόσκληση", "translation": "invitation", "tags": "A1;noun;feminine-eta" },
  { "greek": "πρόταση", "translation": "sentence", "tags": "A1;noun;feminine-eta" },
  { "greek": "πόλη", "translation": "city", "tags": "A1;noun;feminine-eta" },
  { "greek": "σκόνη", "translation": "dust", "tags": "A1;noun;feminine-eta" },
  { "greek": "στήλη", "translation": "column", "tags": "A1;noun;feminine-eta" },
  { "greek": "συγνώμη", "translation": "apology", "tags": "A1;noun;feminine-eta" },
  { "greek": "συζήτηση", "translation": "discussion", "tags": "A1;noun;feminine-eta" },
  { "greek": "συμβουλή", "translation": "advice", "tags": "A1;noun;feminine-eta" },
  { "greek": "συνέντευξη", "translation": "interview", "tags": "A1;noun;feminine-eta" },
  { "greek": "συνταγή", "translation": "recipe", "tags": "A1;noun;feminine-eta" },
  { "greek": "συσκευή", "translation": "device", "tags": "A1;noun;feminine-eta" },
  { "greek": "σχέση", "translation": "relation", "tags": "A1;noun;feminine-eta" },
  { "greek": "σύγκριση", "translation": "comparison", "tags": "A1;noun;feminine-eta" },
  { "greek": "τάξη", "translation": "classroom", "tags": "A1;noun;feminine-eta" },
  { "greek": "τηλεόραση", "translation": "television", "tags": "A1;noun;feminine-eta" },
  { "greek": "τιμή", "translation": "price", "tags": "A1;noun;feminine-eta" },
  { "greek": "τσάντα σχολική", "translation": "schoolbag", "tags": "A1;noun;feminine-eta" },
  { "greek": "υπογραφή", "translation": "signature", "tags": "A1;noun;feminine-eta" },
  { "greek": "υπομονή", "translation": "patience", "tags": "A1;noun;feminine-eta" },
  { "greek": "φήμη", "translation": "rumor", "tags": "A1;noun;feminine-eta" },
  { "greek": "φράση", "translation": "phrase", "tags": "A1;noun;feminine-eta" },
  { "greek": "φωνή", "translation": "voice", "tags": "A1;noun;feminine-eta" },
  { "greek": "φωτογραφική μηχανή", "translation": "camera", "tags": "A1;noun;feminine-eta" },
  { "greek": "φύση", "translation": "nature", "tags": "A1;noun;feminine-eta" },
  { "greek": "χρήση", "translation": "use", "tags": "A1;noun;feminine-eta" },
  { "greek": "έφηβος", "translation": "teenager", "tags": "A1;noun;unisex" },
  { "greek": "αθλητής", "translation": "athlete", "tags": "A1;noun;unisex" },
  { "greek": "απόφοιτος", "translation": "graduate", "tags": "A1;noun;unisex" },
  { "greek": "ασθενής", "translation": "patient", "tags": "A1;noun;unisex" },
  { "greek": "γιατρός", "translation": "doctor", "tags": "A1;noun;unisex" },
  { "greek": "γραμματέας", "translation": "secretary", "tags": "A1;noun;unisex" },
  { "greek": "δημοσιογράφος", "translation": "ournalist", "tags": "A1;noun;unisex" },
  { "greek": "δικηγόρος", "translation": "lawer", "tags": "A1;noun;unisex" },
  { "greek": "κάτοικος", "translation": "resident, inhabitant", "tags": "A1;noun;unisex" },
  { "greek": "καθηγητής", "translation": "teacher", "tags": "A1;noun;unisex" },
  { "greek": "κομμωτής", "translation": "hair dresser", "tags": "A1;noun;unisex" },
  { "greek": "μάγειρας", "translation": "cook", "tags": "A1;noun;unisex" },
  { "greek": "μαθητής", "translation": "pupil, student", "tags": "A1;noun;unisex" },
  { "greek": "νικητής", "translation": "winner", "tags": "A1;noun;unisex" },
  { "greek": "νοσοκόμος", "translation": "nurse", "tags": "A1;noun;unisex" },
  { "greek": "ξάδερφος", "translation": "cousin", "tags": "A1;noun;unisex" },
  { "greek": "οδηγός", "translation": "guide", "tags": "A1;noun;unisex" },
  { "greek": "παθολόγος", "translation": "pathologist", "tags": "A1;noun;unisex" },
  { "greek": "παιδίατρος", "translation": "pediatrician", "tags": "A1;noun;unisex" },
  { "greek": "πελάτης", "translation": "client", "tags": "A1;noun;unisex" },
  { "greek": "πωλητής", "translation": "salesperson, shop assistant", "tags": "A1;noun;unisex" },
  { "greek": "συμμαθητής", "translation": "school mate", "tags": "A1;noun;unisex" },
  { "greek": "συνάδελφος", "translation": "colleague", "tags": "A1;noun;unisex" },
  { "greek": "τουρίστας", "translation": "tourist", "tags": "A1;noun;unisex" },
  { "greek": "φίλος", "translation": "friend", "tags": "A1;noun;unisex" },
  { "greek": "φαρμακοποιός", "translation": "pharmacist", "tags": "A1;noun;unisex" },
  { "greek": "φοιτητής", "translation": "student", "tags": "A1;noun;unisex" },
  { "greek": "φούρναρης", "translation": "baker", "tags": "A1;noun;unisex" },
  { "greek": "χειρούργος", "translation": "surgeon", "tags": "A1;noun;unisex" },
  { "greek": "θυμάμαι", "translation": "to remember", "tags": "A1;verb;gamma3 (-άμαι)" },
  { "greek": "κοιμάμαι", "translation": "to sleep", "tags": "A1;verb;gamma3 (-άμαι)" },
  { "greek": "λυπάμαι", "translation": "to be sorry", "tags": "A1;verb;gamma3 (-άμαι)" },
  { "greek": "φοβάμαι", "translation": "to be afraid of", "tags": "A1;verb;gamma3 (-άμαι)" },
  { "greek": "αρνούμαι", "translation": "to say no, to refuse", "tags": "A1;verb;gamma2 (-ούμαι)" },
  { "greek": "έρχομαι", "translation": "to come", "tags": "A1;verb;gamma (-ομαι)" },
  { "greek": "αισθάνομαι", "translation": "to feel", "tags": "A1;verb;gamma (-ομαι)" },
  { "greek": "απευθύνομαι", "translation": "to address to", "tags": "A1;verb;gamma (-ομαι)" },
  { "greek": "γίνομαι", "translation": "to become", "tags": "A1;verb;gamma (-ομαι)" },
  { "greek": "ετοιμάζομαι", "translation": "to get ready, to be prepared", "tags": "A1;verb;gamma (-ομαι)" },
  { "greek": "κάθομαι", "translation": "to sit", "tags": "A1;verb;gamma (-ομαι)" },
  { "greek": "ντύνομαι", "translation": "to get dressed", "tags": "A1;verb;gamma (-ομαι)" },
  { "greek": "παντρεύομαι", "translation": "to get married", "tags": "A1;verb;gamma (-ομαι)" },
  { "greek": "σκέφτομαι", "translation": "to think", "tags": "A1;verb;gamma (-ομαι)" },
  { "greek": "συνεργάζομαι", "translation": "to work together", "tags": "A1;verb;gamma (-ομαι)" },
  { "greek": "τρελαίνομαι", "translation": "to go crazy", "tags": "A1;verb;gamma (-ομαι)" },
  { "greek": "υπόσχομαι", "translation": "to promise", "tags": "A1;verb;gamma (-ομαι)" },
  { "greek": "φαίνομαι", "translation": "to look like, to appear", "tags": "A1;verb;gamma (-ομαι)" },
  { "greek": "χαίρομαι", "translation": "to be happy, to be pleased", "tags": "A1;verb;gamma (-ομαι)" },
  { "greek": "χρειάζομαι", "translation": "to need", "tags": "A1;verb;gamma (-ομαι)" },
  { "greek": "Ηawaii χαιρετάω", "translation": "to say hello", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "αγαπάω", "translation": "to love", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "βοηθάω", "translation": "to help", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "γελάω", "translation": "to laugh", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "γεννάω", "translation": "to give birth", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "διψάω", "translation": "to be thirsty", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "ζητάω", "translation": "to ask", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "κολυμπάω", "translation": "to swim", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "κρατάω", "translation": "to hold", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "μελετάω", "translation": "to study", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "μετράω", "translation": "to count", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "μιλάω", "translation": "to talk, to speak", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "ξεκινάω", "translation": "to begin, to start", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "ξενυχτάω", "translation": "to stay up (late)", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "ξεχνάω", "translation": "to forget", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "ξυπνάω", "translation": "to wake up", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "περνάω", "translation": "to pass", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "περπατάω", "translation": "to walk", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "πονάω", "translation": "to hurt, to feel pain, to be in pain", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "ρωτάω", "translation": "to ask", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "σταματάω", "translation": "to stop", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "τραγουδάω", "translation": "to sing", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "χτυπάω", "translation": "to hurt, to hit", "tags": "A1;verb;contracted (-άω/-ώ)" },
  { "greek": "ακολουθώ", "translation": "to follow", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "αντικαθιστώ", "translation": "to replace", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "απαντώ", "translation": "to answer, to respond, to reply", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "αργώ", "translation": "to be late (μου)", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "αρκώ", "translation": "to suffice, to be enough", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "δεκαοκτώ", "translation": "eighteen", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "δημιουργώ", "translation": "to create", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "εδώ", "translation": "here", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "επιθυμώ", "translation": "to wish", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "ευχαριστώ", "translation": "to thank", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "καλώ", "translation": "to call, to invite", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "μπορώ", "translation": "can", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "οδηγώ", "translation": "to drive, to guide", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "οκτώχτώ", "translation": "eight", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "παρακαλώ", "translation": "to please (Σε/Σας)", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "παρακολουθώ", "translation": "to watch", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "παρατηρώ", "translation": "to observe", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "προσκαλώ", "translation": "to invite", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "προσπαθώ", "translation": "to try", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "προτιμώ", "translation": "to prefer", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "συζητώ", "translation": "to discuss", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "συναντώ", "translation": "to meet, to come across", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "τηλεφωνώ", "translation": "to call", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "χρησιμοποιώ", "translation": "to use", "tags": "A1;verb;contracted (-ώ)" },
  { "greek": "έχω", "translation": "to have", "tags": "A1;verb;omega" },
  { "greek": "αγοράζω", "translation": "to buy", "tags": "A1;verb;omega" },
  { "greek": "αδειάζω", "translation": "to empty", "tags": "A1;verb;omega" },
  { "greek": "αδυνατίζω", "translation": "to get thin, to get slim, to lose weight", "tags": "A1;verb;omega" },
  { "greek": "ακούω", "translation": "to hear, to listen", "tags": "A1;verb;omega" },
  { "greek": "αλλάζω", "translation": "to change", "tags": "A1;verb;omega" },
  { "greek": "ανάβω", "translation": "to light, to fire", "tags": "A1;verb;omega" },
  { "greek": "αναγνωρίζω", "translation": "to recognize", "tags": "A1;verb;omega" },
  { "greek": "ανακατεύω", "translation": "to mix, to blend", "tags": "A1;verb;omega" },
  { "greek": "αναπνέω", "translation": "to breathe", "tags": "A1;verb;omega" },
  { "greek": "αναφέρω", "translation": "to refer, to mention", "tags": "A1;verb;omega" },
  { "greek": "ανεβαίνω", "translation": "to climb, to get on", "tags": "A1;verb;omega" },
  { "greek": "ανοίγω", "translation": "to open", "tags": "A1;verb;omega" },
  { "greek": "αντιστοιχίζω", "translation": "to match", "tags": "A1;verb;omega" },
  { "greek": "αποφασίζω", "translation": "to decide", "tags": "A1;verb;omega" },
  { "greek": "αποφεύγω", "translation": "to avoid", "tags": "A1;verb;omega" },
  { "greek": "αρρωσταίνω", "translation": "to become sick/ill, to get sick/ill", "tags": "A1;verb;omega" },
  { "greek": "αρχίζω", "translation": "to begin, to start", "tags": "A1;verb;omega" },
  { "greek": "αφήνω", "translation": "to leave, to let", "tags": "A1;verb;omega" },
  { "greek": "βάζω", "translation": "to put", "tags": "A1;verb;omega" },
  { "greek": "βάφω", "translation": "to paint", "tags": "A1;verb;omega" },
  { "greek": "βήχω", "translation": "to cough", "tags": "A1;verb;omega" },
  { "greek": "βγάζω", "translation": "to take out, to take off", "tags": "A1;verb;omega" },
  { "greek": "βγαίνω", "translation": "to get out", "tags": "A1;verb;omega" },
  { "greek": "βλέπω", "translation": "to see, to look, to watch", "tags": "A1;verb;omega" },
  { "greek": "βρέχω", "translation": "to wet", "tags": "A1;verb;omega" },
  { "greek": "βρίσκω", "translation": "to find", "tags": "A1;verb;omega" },
  { "greek": "γεμίζω", "translation": "to fill", "tags": "A1;verb;omega" },
  { "greek": "γνωρίζω", "translation": "to know", "tags": "A1;verb;omega" },
  { "greek": "γράφω", "translation": "to write", "tags": "A1;verb;omega" },
  { "greek": "γυρίζω", "translation": "to come back", "tags": "A1;verb;omega" },
  { "greek": "δίνω", "translation": "to give", "tags": "A1;verb;omega" },
  { "greek": "δείχνω", "translation": "to show", "tags": "A1;verb;omega" },
  { "greek": "διαβάζω", "translation": "to read", "tags": "A1;verb;omega" },
  { "greek": "διαγράφω", "translation": "to delete, to erase", "tags": "A1;verb;omega" },
  { "greek": "διακρίνω", "translation": "to distinguish", "tags": "A1;verb;omega" },
  { "greek": "διαλέγω", "translation": "to choose", "tags": "A1;verb;omega" },
  { "greek": "διασκεδάζω", "translation": "to have fun, to enoy myself", "tags": "A1;verb;omega" },
  { "greek": "διδάσκω", "translation": "to teach", "tags": "A1;verb;omega" },
  { "greek": "διορθώνω", "translation": "to correct", "tags": "A1;verb;omega" },
  { "greek": "δοκιμάζω", "translation": "to try", "tags": "A1;verb;omega" },
  { "greek": "δουλεύω", "translation": "to work", "tags": "A1;verb;omega" },
  { "greek": "επιλέγω", "translation": "to chose", "tags": "A1;verb;omega" },
  { "greek": "επιστρέφω", "translation": "to come back", "tags": "A1;verb;omega" },
  { "greek": "επιτρέπω", "translation": "to allow", "tags": "A1;verb;omega" },
  { "greek": "ετοιμάζω", "translation": "to prepare", "tags": "A1;verb;omega" },
  { "greek": "ζω", "translation": "to live", "tags": "A1;verb;omega" },
  { "greek": "ζωγραφίζω", "translation": "to paint", "tags": "A1;verb;omega" },
  { "greek": "θέλω", "translation": "to want", "tags": "A1;verb;omega" },
  { "greek": "κάνω", "translation": "to do", "tags": "A1;verb;omega" },
  { "greek": "κάτω", "translation": "down", "tags": "A1;verb;omega" },
  { "greek": "καθαρίζω", "translation": "to clean", "tags": "A1;verb;omega" },
  { "greek": "καλωσορίζω", "translation": "to welcome", "tags": "A1;verb;omega" },
  { "greek": "καλύπτω", "translation": "to cover", "tags": "A1;verb;omega" },
  { "greek": "καταλαβαίνω", "translation": "to understand", "tags": "A1;verb;omega" },
  { "greek": "κατεβαίνω", "translation": "to get down", "tags": "A1;verb;omega" },
  { "greek": "κερδίζω", "translation": "to win", "tags": "A1;verb;omega" },
  { "greek": "κλείνω", "translation": "to close, to shut, to turn off", "tags": "A1;verb;omega" },
  { "greek": "κολλάω", "translation": "to stick", "tags": "A1;verb;omega" },
  { "greek": "κρίνω", "translation": "to udge", "tags": "A1;verb;omega" },
  { "greek": "κρύβω", "translation": "to hide", "tags": "A1;verb;omega" },
  { "greek": "κυκλώνω", "translation": "to circle", "tags": "A1;verb;omega" },
  { "greek": "κόβω", "translation": "to cut", "tags": "A1;verb;omega" },
  { "greek": "λέω", "translation": "to say", "tags": "A1;verb;omega" },
  { "greek": "λείπω", "translation": "to be absent", "tags": "A1;verb;omega" },
  { "greek": "λύνω", "translation": "to solve", "tags": "A1;verb;omega" },
  { "greek": "μένω", "translation": "to stay, to live", "tags": "A1;verb;omega" },
  { "greek": "μαγειρεύω", "translation": "to cook", "tags": "A1;verb;omega" },
  { "greek": "μαζεύω", "translation": "gather", "tags": "A1;verb;omega" },
  { "greek": "μαθαίνω", "translation": "to learn", "tags": "A1;verb;omega" },
  { "greek": "μεταφράζω", "translation": "to translate", "tags": "A1;verb;omega" },
  { "greek": "μοιάζω", "translation": "to look like", "tags": "A1;verb;omega" },
  { "greek": "μοιράζω", "translation": "to distribute, to deliver", "tags": "A1;verb;omega" },
  { "greek": "μπαίνω", "translation": "to get into, to enter", "tags": "A1;verb;omega" },
  { "greek": "μυρίζω", "translation": "to smell", "tags": "A1;verb;omega" },
  { "greek": "νιώθω", "translation": "to feel", "tags": "A1;verb;omega" },
  { "greek": "νοικιάζω", "translation": "to rent", "tags": "A1;verb;omega" },
  { "greek": "νομίζω", "translation": "to think", "tags": "A1;verb;omega" },
  { "greek": "ξέρω", "translation": "to know", "tags": "A1;verb;omega" },
  { "greek": "ξεφεύγω", "translation": "to escape, to get away", "tags": "A1;verb;omega" },
  { "greek": "ξοδεύω", "translation": "to spend", "tags": "A1;verb;omega" },
  { "greek": "πάνω", "translation": "up", "tags": "A1;verb;omega" },
  { "greek": "πέφτω", "translation": "to fall", "tags": "A1;verb;omega" },
  { "greek": "πίνω", "translation": "to drink", "tags": "A1;verb;omega" },
  { "greek": "πίσω", "translation": "behind", "tags": "A1;verb;omega" },
  { "greek": "παίζω", "translation": "to play", "tags": "A1;verb;omega" },
  { "greek": "παίρνω", "translation": "to take", "tags": "A1;verb;omega" },
  { "greek": "παραγγέλνω", "translation": "to order", "tags": "A1;verb;omega" },
  { "greek": "παρακάτω", "translation": "below", "tags": "A1;verb;omega" },
  { "greek": "παραπάνω", "translation": "above", "tags": "A1;verb;omega" },
  { "greek": "παρουσιάζω", "translation": "to present", "tags": "A1;verb;omega" },
  { "greek": "πεινάω", "translation": "to be hungry", "tags": "A1;verb;omega" },
  { "greek": "περιγράφω", "translation": "to describe", "tags": "A1;verb;omega" },
  { "greek": "περιμένω", "translation": "to wait", "tags": "A1;verb;omega" },
  { "greek": "πηγαίνω", "translation": "to go", "tags": "A1;verb;omega" },
  { "greek": "πιάνω", "translation": "to touch", "tags": "A1;verb;omega" },
  { "greek": "πιστεύω", "translation": "to believe", "tags": "A1;verb;omega" },
  { "greek": "πλένω", "translation": "to wash", "tags": "A1;verb;omega" },
  { "greek": "πληρώνω", "translation": "to pay", "tags": "A1;verb;omega" },
  { "greek": "ποτίζω", "translation": "water", "tags": "A1;verb;omega" },
  { "greek": "πουλάω", "translation": "to sell", "tags": "A1;verb;omega" },
  { "greek": "προετοιμάζω", "translation": "to prepare", "tags": "A1;verb;omega" },
  { "greek": "προσέχω", "translation": "to pay attention to", "tags": "A1;verb;omega" },
  { "greek": "προσφέρω", "translation": "to offer", "tags": "A1;verb;omega" },
  { "greek": "προτείνω", "translation": "to suggest, to propose", "tags": "A1;verb;omega" },
  { "greek": "προφέρω", "translation": "to pronounce", "tags": "A1;verb;omega" },
  { "greek": "ρίχνω", "translation": "to throw", "tags": "A1;verb;omega" },
  { "greek": "σβήνω", "translation": "to rub, to erase", "tags": "A1;verb;omega" },
  { "greek": "σερβίρω", "translation": "to serve", "tags": "A1;verb;omega" },
  { "greek": "σημαίνω", "translation": "to mean", "tags": "A1;verb;omega" },
  { "greek": "σημειώνω", "translation": "to note, to make a note, to write down", "tags": "A1;verb;omega" },
  { "greek": "σκουπίζω", "translation": "to sweep", "tags": "A1;verb;omega" },
  { "greek": "σπουδάζω", "translation": "to study", "tags": "A1;verb;omega" },
  { "greek": "στέλνω", "translation": "to send", "tags": "A1;verb;omega" },
  { "greek": "στολίζω", "translation": "to decorate", "tags": "A1;verb;omega" },
  { "greek": "συγκρίνω", "translation": "to compare", "tags": "A1;verb;omega" },
  { "greek": "συμβουλεύω", "translation": "to advise", "tags": "A1;verb;omega" },
  { "greek": "συμμετέχω", "translation": "to participate in, to take part in", "tags": "A1;verb;omega" },
  { "greek": "συμπληρώνω", "translation": "to complete, to fill", "tags": "A1;verb;omega" },
  { "greek": "συνδέω", "translation": "to connect", "tags": "A1;verb;omega" },
  { "greek": "συνεχίζω", "translation": "to continue, to go on", "tags": "A1;verb;omega" },
  { "greek": "συστήνω", "translation": "to introduce, to recomend", "tags": "A1;verb;omega" },
  { "greek": "σφουγγαρίζω", "translation": "to mop", "tags": "A1;verb;omega" },
  { "greek": "σχεδιάζω", "translation": "to plan", "tags": "A1;verb;omega" },
  { "greek": "ταιριάζω", "translation": "to fit", "tags": "A1;verb;omega" },
  { "greek": "ταξιδεύω", "translation": "to travel, to take a trip, to make a ourney", "tags": "A1;verb;omega" },
  { "greek": "τελειώνω", "translation": "to finish", "tags": "A1;verb;omega" },
  { "greek": "τηγανίζω", "translation": "to fry", "tags": "A1;verb;omega" },
  { "greek": "τονίζω", "translation": "to put accent on", "tags": "A1;verb;omega" },
  { "greek": "τρέχω", "translation": "run", "tags": "A1;verb;omega" },
  { "greek": "τρακάρω", "translation": "to crash", "tags": "A1;verb;omega" },
  { "greek": "τριγυρνάω", "translation": "to wander", "tags": "A1;verb;omega" },
  { "greek": "τρώω", "translation": "to eat", "tags": "A1;verb;omega" },
  { "greek": "υπάρχω", "translation": "to exist", "tags": "A1;verb;omega" },
  { "greek": "υπογράφω", "translation": "to sign", "tags": "A1;verb;omega" },
  { "greek": "υπογραμμίζω", "translation": "underline", "tags": "A1;verb;omega" },
  { "greek": "φέρνω", "translation": "to bring", "tags": "A1;verb;omega" },
  { "greek": "φεύγω", "translation": "to leave", "tags": "A1;verb;omega" },
  { "greek": "φοράω", "translation": "to wear", "tags": "A1;verb;omega" },
  { "greek": "φτάνω", "translation": "to arrive", "tags": "A1;verb;omega" },
  { "greek": "φτιάχνω", "translation": "to make", "tags": "A1;verb;omega" },
  { "greek": "φωνάζω", "translation": "to yell, to speak out loud", "tags": "A1;verb;omega" },
  { "greek": "χάνω", "translation": "to lose", "tags": "A1;verb;omega" },
  { "greek": "χαλάω", "translation": "to break, to break down", "tags": "A1;verb;omega" },
  { "greek": "χαλαρώνω", "translation": "to loose", "tags": "A1;verb;omega" },
  { "greek": "χαρακτηρίζω", "translation": "to characterize", "tags": "A1;verb;omega" },
  { "greek": "χορεύω", "translation": "to dance", "tags": "A1;verb;omega" },
  { "greek": "χωρίζω", "translation": "to separate", "tags": "A1;verb;omega" },
  { "greek": "ψάχνω", "translation": "to search, to look for", "tags": "A1;verb;omega" },
  { "greek": "ψαρεύω", "translation": "to fish", "tags": "A1;verb;omega" },
  { "greek": "ψωνίζω", "translation": "to shop, to go shopping", "tags": "A1;verb;omega" }
];
